import { useState } from 'react';
import { useReveal } from '../hooks/useReveal';

const TABS = ['Developer', 'Marketing', 'Finance', 'Security'] as const;

const PANELS: Array<{
  badge: string;
  title: string;
  desc: string;
  feats: string[];
  visual: 'developer' | 'marketing' | 'finance' | 'security';
}> = [
  {
    badge: 'Developer Agent',
    title: 'Build anything from a prompt.',
    desc: 'Websites, mobile apps, APIs, and full-stack software — generated, tested, and deployed by your agent.',
    feats: [
      'Full-stack apps from natural language',
      'Responsive designs with custom branding',
      'One-click deploy to Buildor hosting',
    ],
    visual: 'developer',
  },
  {
    badge: 'Marketing Agent',
    title: 'Campaigns that run themselves.',
    desc: 'Copy, social media, email campaigns, analytics — your marketing agent handles the full funnel.',
    feats: [
      'Write copy for any channel or audience',
      'Analyze performance with AI insights',
      'Schedule and manage social content',
    ],
    visual: 'marketing',
  },
  {
    badge: 'Finance Agent',
    title: 'Your books, on autopilot.',
    desc: 'Bookkeeping, invoicing, expense tracking, and financial reports — all managed by your AI accountant.',
    feats: [
      'Auto-generate and send invoices',
      'Real-time financial dashboards',
      'Tax prep and compliance reports',
    ],
    visual: 'finance',
  },
  {
    badge: 'Security Agent',
    title: 'AI technician that never sleeps.',
    desc: 'More than antivirus — an intelligent agent that monitors, maintains, repairs, and optimizes your entire system.',
    feats: [
      'Real-time threat detection and removal',
      'Automatic system repairs and optimization',
      'Full system health monitoring dashboard',
    ],
    visual: 'security',
  },
];

function DeveloperVisual(): JSX.Element {
  return (
    <div className="agent-visual">
      <div className="av-head">
        <div className="av-dot" style={{ background: 'var(--green)', animation: 'blink 2s infinite' }} />
        <div className="av-title">client-site.buildor.app</div>
      </div>
      <div className="av-content">
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', color: 'var(--text-5)', marginBottom: '8px' }}>
          // Generated by SiteBuilder agent
        </div>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', lineHeight: 1.8 }}>
          <span style={{ color: 'var(--purple)' }}>export default</span>{' '}
          <span style={{ color: 'var(--cyan)' }}>function</span>{' '}
          <span style={{ color: 'var(--green)' }}>LandingPage</span>
          () {'{'}
          <br />
          &nbsp;&nbsp;<span style={{ color: 'var(--purple)' }}>return</span> (
          <br />
          &nbsp;&nbsp;&nbsp;&nbsp;&lt;<span style={{ color: 'var(--cyan)' }}>Hero</span>{' '}
          <span style={{ color: 'var(--orange)' }}>title</span>=<span style={{ color: 'var(--green)' }}>&quot;Welcome&quot;</span> /&gt;
          <br />
          &nbsp;&nbsp;)
          <br />
          {'}'}
        </div>
      </div>
    </div>
  );
}

function MarketingVisual(): JSX.Element {
  const heights = ['35%', '48%', '42%', '60%', '55%', '75%', '68%', '90%'];
  return (
    <div className="agent-visual">
      <div className="av-head">
        <div className="av-dot" style={{ background: 'var(--purple)' }} />
        <div className="av-title">Campaign Dashboard</div>
      </div>
      <div className="av-content">
        <div className="av-stat-row" style={{ marginBottom: '16px' }}>
          <div className="av-stat">
            <span>+48%</span> Engagement
          </div>
          <div className="av-stat">
            <span>12.4K</span> Reach
          </div>
        </div>
        <div className="av-chart">
          {heights.map((h, i) => (
            <div
              key={i}
              className="av-bar"
              style={{
                height: h,
                background: 'var(--purple)',
                opacity: 0.3 + (i + 1) * 0.1,
              }}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

function FinanceVisual(): JSX.Element {
  const heights = ['30%', '45%', '50%', '40%', '65%', '58%', '82%', '95%'];
  return (
    <div className="agent-visual">
      <div className="av-head">
        <div className="av-dot" style={{ background: 'var(--green)', animation: 'blink 2s infinite' }} />
        <div className="av-title">Finance Overview</div>
      </div>
      <div className="av-content">
        <div className="av-big-num">$24,850</div>
        <div style={{ fontSize: '13px', color: 'var(--text-5)', marginBottom: '16px' }}>Monthly Revenue</div>
        <div className="av-chart">
          {heights.map((h, i) => (
            <div
              key={i}
              className="av-bar"
              style={{
                height: h,
                background: 'var(--green)',
                opacity: 0.3 + (i + 1) * 0.1,
              }}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

function SecurityVisual(): JSX.Element {
  return (
    <div className="agent-visual">
      <div className="av-head">
        <div className="av-dot" style={{ background: 'var(--green)', animation: 'blink 2s infinite' }} />
        <div className="av-title">System Security</div>
      </div>
      <div className="av-content" style={{ textAlign: 'center', paddingTop: '20px' }}>
        <div style={{ fontSize: '48px', marginBottom: '12px' }}>🛡️</div>
        <div style={{ fontFamily: 'var(--font-heading)', fontSize: '20px', fontWeight: 600, color: 'var(--green)', marginBottom: '4px' }}>
          All clear
        </div>
        <div style={{ fontSize: '13px', color: 'var(--text-4)', marginBottom: '16px' }}>0 threats detected</div>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: '12px', color: 'var(--text-5)' }}>CPU: 12% • RAM: 4.2GB</div>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: '12px', color: 'var(--text-5)', marginTop: '4px' }}>
          Last repair: 2h ago
        </div>
      </div>
    </div>
  );
}

function AgentVisual({ type }: { type: 'developer' | 'marketing' | 'finance' | 'security' }): JSX.Element {
  switch (type) {
    case 'developer':
      return <DeveloperVisual />;
    case 'marketing':
      return <MarketingVisual />;
    case 'finance':
      return <FinanceVisual />;
    case 'security':
      return <SecurityVisual />;
  }
}

export function AgentsSection(): JSX.Element {
  const [tab, setTab] = useState(0);
  const headerRef = useReveal<HTMLDivElement>();
  const tabRef = useReveal<HTMLDivElement>();
  const panelRef = useReveal<HTMLDivElement>();

  return (
    <section className="agents-section" id="agents">
      <div className="wrap">
        <div className="agents-header rv" ref={headerRef}>
          <div className="section-label">Agent Types</div>
          <div className="section-title">
            An agent for <span className="cyan-accent">every</span> job.
          </div>
          <p className="section-desc">Build specialized AI workers in minutes. Each agent understands its domain and uses all Buildor tools.</p>
        </div>

        <div className="tab-bar rv rv-d1" ref={tabRef}>
          {TABS.map((label, i) => (
            <button
              key={label}
              type="button"
              className={`tab-btn ${tab === i ? 'on' : ''}`}
              onClick={() => setTab(i)}
            >
              {label}
            </button>
          ))}
        </div>

        {PANELS.map((panel, i) => (
          <div
            key={panel.badge}
            className={`agent-panel rv rv-d2 ${tab === i ? 'on' : ''}`}
            ref={i === 0 ? panelRef : undefined}
          >
            <div>
              <div className="agent-badge">{panel.badge}</div>
              <h3>{panel.title}</h3>
              <p>{panel.desc}</p>
              <div className="agent-feats">
                {panel.feats.map((f) => (
                  <div key={f} className="agent-feat">
                    <div className="check" />
                    {f}
                  </div>
                ))}
              </div>
            </div>
            <AgentVisual type={panel.visual} />
          </div>
        ))}
      </div>
    </section>
  );
}

export default AgentsSection;
